services:
  cgi:
    image: bitnami/php-fpm
  wordpress:
    image: wordpress
    # restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: eureka
      WORDPRESS_DB_PASSWORD: eureka
      WORDPRESS_DB_NAME: software-systems-website
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
  database:
    image: mysql:lts
    # restart: always
    environment:
      MYSQL_DATABASE: eureka
      MYSQL_USER: eureka
      MYSQL_PASSWORD: eureka
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/mysql
volumes:
    wordpress:
    database:
